### ISSUE TITLE
Randomly returning different results for same data:   "parse_errors": []

### ISSUE THREAD

**Issue by ssbarnea** [python-jsonschema/check-jsonschema#218] opened 2023-01-04 20:55 UTC
It seems that check-jsonschema does randomly happens to return either `"parse_errors": []` or missing the entire `parse_errors` key.

While everything else is the same, this randomness is enough in order to break unitests that assert the result outcome.

The logical meaning is the same, having an empty "parse_errors" entry is the same as not having one, but that does not make the API as predictable.

I think that it would be wise to either decide on one or another. Any predictable behavior is better than unpredictable one.

For the moment I find myself forced to add a sanitization wrapper in order to make the results stable.

**Comment by sirosen** [comment] 2023-01-04 21:31
I don't have enough information to reproduce this or even to really start trying to run it down.
Can you provide an example of an input+schema which demonstrates this behavior?

I think it's also worth noting that `parse_errors` and `errors` are sibling keys in the JSON output, and it should be entirely possible to have `"parse_errors": []` in a failing check. For example:
```bash
$ check-jsonschema -o json --schemafile <(echo '{"type": "integer"}') <(echo '"foo"')
{
  "status": "fail",
  "errors": [
    {
      "filename": "/proc/self/fd/17",
      "path": "$",
      "message": "'foo' is not of type 'integer'",
      "has_sub_errors": false
    }
  ],
  "parse_errors": []
}
```

**Comment by ssbarnea** [comment] 2023-01-04 21:41
This is what I had to do to make the outcome consistent between runs. https://github.com/ansible-community/molecule/blob/main/tools/test-schema/src/schema.spec.ts#L30-L43

And yes, I can confirm that this happened when `errors` had content. Still, the outcome was random, sometimes the key was present, sometimes not.

It took me a while to figureout what was happening because it has the tendency of keeping the same result on the same machine (not guaranteed but more likely to keep). Still when running on other machines on CI/CD the results were different. This happened even after pinning the exact versions of the libraries, just to be sure that the difference does not come from different versions. 

Is is not the first time when jsonschema library returned inconsistent results. About an year ago we had serious issues with the order of the errors reported. Luckily this was sorted.

**Comment by sirosen** [comment] 2023-01-04 22:27
The reporter code which populates `parse_errors` is rather simple:
https://github.com/python-jsonschema/check-jsonschema/blob/4b23e71f8a49a5f8ad3a9541845017bd892ae530/src/check_jsonschema/reporter.py#L174-L180

There's no other place where `parse_errors` may or may not be populated, and you'll note that this is running `list(<some-iterable>)`. I can't imagine a way in which the key would be missing _unless_ you are intermittently passing `-q` or otherwise modifying verbosity.

The nearest thing I can imagine ways in which unquoted args could word split, e.g. `instance_file="-qq bar.json"; check-jsonschema --schemafile foo.json $instance_file`.
(This is bad because word splitting applies and `-qq` gets passed.)

---

I won't say that what you describe is impossible, but right now I'm missing any information or breadcrumbs necessary to see how it _is_ possible.

Have you been able to reproduce this behavior outside of your CI context?
I don't have enough information here to try to run this down.

**Comment by sirosen** [comment] 2023-01-05 04:42
I've looked at the `ansible-community/molecule` repo for clues. And I _do_ see CI runs in which this appears to be in play (e.g. https://github.com/ansible-community/molecule/actions/runs/3841134372/jobs/6541002780).

However, those cases are showing me something quite different from `parse_errors` disappearing.
The failures appear on commits like [this one](https://github.com/ansible-community/molecule/commit/d6bb84ddd5a9050186c2265980d4219593f3ed89) in which the `parse_errors` block was _removed by the commit_. Then things run in CI and the key is present, as it should be.

So then the question becomes "how did that get removed?" `check-jsonschema>=0.18.0` always produces it in the output (at default verbosity).

However, I can rather trivially reproduce the removal with
```
pipx install check-jsonschema==0.17.0 --force
cd tools/test-schema/
npm install && npm test
```

I very strongly suspect that this is the cause. The "schema" pre-commit hook in that repo calls whatever version of `check-jsonschema` is installed, which means that the behavior is not guaranteed to be consistent across runners and environments because the version isn't being controlled.

As such, and absent any evidence to the contrary, I'm removing the bug label and closing this as not-a-bug. I'm more than happy to revisit this if there's new or further evidence that `check-jsonschema` is behaving unexpectedly.

**Closed by sirosen** 2023-01-05 04:42 UTC
Labels: needs-investigation
