### ISSUE TITLE
[BUG] UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1571: character maps to <undefined>

### ISSUE THREAD

**Issue by adam-grant-hendry** [python-jsonschema/check-jsonschema#74] opened 2022-04-13 06:06 UTC
**System:**
OS: Windows 10 x64-bit
`python-jsonschema`: 0.14.2
hooks: `check-github-workflows`

**Issue:**
Running hook id `check-github-workflows` through `pre-commit` gives the following error:

```bash
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hendra11\.cache\pre-commit\repobbwlicnh\py_env-python3.8\Scripts\check-jsonschema.EXE\__main__.py", line 7, in <module>     
  File "C:\Users\hendra11\.cache\pre-commit\repobbwlicnh\py_env-python3.8\lib\site-packages\check_jsonschema\__init__.py", line 26, in main  
    ret = checker.run()
  File "C:\Users\hendra11\.cache\pre-commit\repobbwlicnh\py_env-python3.8\lib\site-packages\check_jsonschema\checker.py", line 88, in run    
    self._run()
  File "C:\Users\hendra11\.cache\pre-commit\repobbwlicnh\py_env-python3.8\lib\site-packages\check_jsonschema\checker.py", line 71, in _run   
    errors = self._build_error_map()
  File "C:\Users\hendra11\.cache\pre-commit\repobbwlicnh\py_env-python3.8\lib\site-packages\check_jsonschema\checker.py", line 61, in _build_error_map
    for filename, doc in self._instance_loader.iter_files():
  File "C:\Users\hendra11\.cache\pre-commit\repobbwlicnh\py_env-python3.8\lib\site-packages\check_jsonschema\loaders\instance\__init__.py", line 62, in iter_files
    data = loadfunc(fp)
  File "C:\Users\hendra11\.cache\pre-commit\repobbwlicnh\py_env-python3.8\lib\site-packages\ruamel\yaml\main.py", line 343, in load
    return constructor.get_single_data()
  File "C:\Users\hendra11\.cache\pre-commit\repobbwlicnh\py_env-python3.8\lib\site-packages\ruamel\yaml\constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 701, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 902, in _ruamel_yaml.CParser._parse_next_event
  File "_ruamel_yaml.pyx", line 911, in _ruamel_yaml.input_handler
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1571: character maps to <undefined>
```

**Comment by sirosen** [comment] 2022-04-13 19:53
I've just released a fix for this in v0.14.3 which changes the above line to `open(fn, encoding="utf-8")`.
This should fix the issue, but please let me know if you see any trouble with it!

I also added a new test for this, which I confirmed was failing on GitHub Actions windows builds without the fix.

**Closed by sirosen** 2022-04-13 19:53 UTC
Labels: bug

**Comment by adam-grant-hendry** [comment] 2022-04-15 01:57
Thank you @sirosen ! You are an excellent maintainer. Thank you for responding so quickly. I can confirm on my end that this solves my problem. Thank you!

**Comment by YakBizzarro** [comment] 2025-02-17 12:50
I have the same problem, running on WIndows 10. Downgrading to 0.14.3 solved, but on 0.31.1 the problem persist. Any suggestion? thank you!

**Comment by sirosen** [comment] 2025-02-17 13:45
@YakBizzarro, could you please open a new issue and include the stack trace you got? The original issue here shouldn't be possible anymore since most of the time we're now reading files as bytes with no encoding.

Without a traceback, I don't think I'll be able to investigate.

**Comment by YakBizzarro** [comment] 2025-03-13 09:54
after a rebase, the error is gone and I can't reproduce it anymore. If it will happen in future, I'll open a ticket. sorry for the noise and thanks for the help!
