### ISSUE TITLE
Unable to download new redirected schema from SchemaStore.

### ISSUE THREAD

**Issue by GerryFerdinandus** [python-jsonschema/check-jsonschema#71] opened 2022-04-11 18:33 UTC
There is a problem with SchemaStore PR https://github.com/SchemaStore/schemastore/pull/2040. I don't know what the real cause of the problem is.
The JSON schema is removed and the catalog list is updated with the new reference. And from what I understand, this plugin would not use the new redirected JSON schema. Can you look at this?
I assume that when the catalog is updated with a newer data timestamp than the JSON schema cache time, it will download a new JSON schema from the new updated catalog URL link.

**Comment by dudicoco** [comment] 2022-04-11 18:56
I believe this can be closed, seems like there was a misunderstanding.
See https://github.com/SchemaStore/schemastore/pull/2040#issuecomment-1095435895

**Comment by sirosen** [comment] 2022-04-11 18:56
I can look into this after I'm off the clock today, but I don't think there's any bug or issue here. `check-jsonschema` has support for downloading schemas over HTTPS, e.g. `--schemafile https://foo.example.com/schema.json`, and it sounds like some user had that pointed at the URL of a schema which was removed from schemastore? So they should just update to the new location of that schema, wherever it is.

**Comment by sirosen** [comment] 2022-04-12 16:21
I've done a more careful review of the schemastore PR thread. There's no action here, so I'm closing.

@GerryFerdinandus, just in case it gets mentioned to you again, `check-jsonschema` is just a python CLI tool for running JSON Schema validation. It doesn't parse the schemastore catalog or have other "advanced" features. Hopefully you never have to stop by again because everything works as intended, but I'm always happy to take bugs or feature requests. 🙂

**Closed by sirosen** 2022-04-12 16:21 UTC
Labels: invalid
