### ISSUE TITLE
Bug with field named 'type' definition in '$defs'

### ISSUE THREAD

**Issue by nicotrozzo** [python-jsonschema/check-jsonschema#317] opened 2023-08-30 20:11 UTC
Hi,
I think I've reached a bug when using a definition called `type`. 

This is the minimal example I could build to reproduce the situation:

## Input

`test.json` file:
```json
{
    "$schema": "test.schema.json",
    "type": "test"
}
```
## Failing schema
`test.schema.json`
```json
{
    "$schema": "http://json-schema.org/schema",
    "properties": {
        "type": {
            "$ref": "#/$defs/definitionGroup/type"
        }
    },
    "$defs": {
        "definitionGroup": {
            "type": {
                "type": "string",
                "description": "'type' description"
            }
        }
    }
}
```

Running `check-jsonschema` produces the following output:
```bash
$ check-jsonschema test.json --schemafile test.schema.json 
Error: schemafile was not valid: {'type': 'string', 'description': "'type' description"} is not valid under any of the given schemas

Failed validating 'anyOf' in metaschema['allOf'][0]['properties']['$defs']['additionalProperties']['$dynamicRef']['allOf'][3]['properties']['type']:
    {'anyOf': [{'$ref': '#/$defs/simpleTypes'},
               {'items': {'$ref': '#/$defs/simpleTypes'},
                'minItems': 1,
                'type': 'array',
                'uniqueItems': True}]}

On schema['$defs']['definitionGroup']['type']:
    {'description': "'type' description", 'type': 'string'}

SchemaError: {'type': 'string', 'description': "'type' description"} is not valid under any of the given schemas

Failed validating 'anyOf' in metaschema['allOf'][0]['properties']['$defs']['additionalProperties']['$dynamicRef']['allOf'][3]['properties']['type']:
    {'anyOf': [{'$ref': '#/$defs/simpleTypes'},
               {'items': {'$ref': '#/$defs/simpleTypes'},
                'minItems': 1,
                'type': 'array',
                'uniqueItems': True}]}

On schema['$defs']['definitionGroup']['type']:
    {'description': "'type' description", 'type': 'string'}
  in "/home/ntrozzo/.local/lib/python3.10/site-packages/check_jsonschema/checker.py", line 52
  >>> return self._schema_loader.get_validator(
```

If the definition is not inside `definitionGroup` it does not fail.

## Schema fixed
Changing the definition name to `types` instead of `type` makes the validation pass:
`test.schema.json`:
```json
{
    "$schema": "http://json-schema.org/schema",
    "properties": {
        "type": {
            "$ref": "#/$defs/definitionGroup/types"
        }
    },
    "$defs": {
        "definitionGroup": {
            "types": {
                "type": "string",
                "description": "'type' description"
            }
        }
    }
}
```

The output changes to:
```bash
$ check-jsonschema test.json --schemafile test.schema.json 
ok -- validation done
```

To be honest, I have not checked the JSON Schema spec to know if this is a valid schema or not, but it works fine using the JSON Schema VScode extension and it fails when using `check-jsonschema`.
It took me a while to realise where the error was, and I think it's possibly a bug because the `type` keyword could be easily hardcoded somewhere.

## check-jsonschema version
```bash
$ check-jsonschema --version
check-jsonschema, version 0.23.2
```
I'm running this on Ubuntu 22.

**Comment by sirosen** [comment] 2023-08-30 20:56
The schema is what I would call "borderline invalid" because it contains an ambiguity.
That ambiguity allow different validators to change how it is parsed and raise (or not raise) an error.

The issue is that `$schema` is not a valid metaschema, so the behavior you're seeing from `check-jsonschema` is to failover to the latest draft (2020). I'm guessing that VS Code has some earlier default, like draft7.

You can fix more or less trivially by setting `$schema` to draft7:
```
    "$schema": "http://json-schema.org/draft-07/schema#"
```

This will pass in `check-jsonschema` because that draft does not strictly specify the contents of `$defs`.

Under later drafts, however, the values in `$defs` are required to each be valid schemas. Nesting in the manner of your original schema is disallowed.

[From the current spec](https://json-schema.org/draft/2020-12/json-schema-core.html#section-8.2.4):
> The "$defs" keyword reserves a location for schema authors to inline re-usable JSON Schemas into a more general schema. The keyword does not directly affect the validation result.
>
> This keyword's value MUST be an object. Each member value of this object MUST be a valid JSON Schema.

Initially I thought maybe there was room for an improvement here, but after thinking about it I'm not so sure. `check-jsonschema` is doing a relatively reasonable thing IMO, just not perfectly aligned with another tool's equally reasonable approach.

I'm closing, since this is not a bug, but I am open to ways of improving this. (I'm just really unsure how.)

**Closed by sirosen** 2023-08-30 20:56 UTC
Labels: question

**Comment by nicotrozzo** [comment] 2023-08-30 21:07
Got it!
Changing to draft07 makes validation pass.
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "type": {
            "$ref": "#/$defs/definitionGroup/type"
        }
    },
    "$defs": {
        "definitionGroup": {
            "type": {
                "type": "string",
                "description": "'type' description"
            }
        }
    }
}
```

Anyway, in my use case I'll change the definition to comply with the current spec, and maybe this issue helps somebody else in the future.

Thank you very much!
