### ISSUE TITLE
Scipt hanging with json input not complying with schema

### ISSUE THREAD

**Issue by nicotrozzo** [python-jsonschema/check-jsonschema#318] opened 2023-08-30 21:25 UTC
Hi, I've reached a situation difficult to reproduce.

I have a rather complex schema file (no nested files though) and a json input file that I know does not comply with some regular expressions in some fields because the VScode extension marked the problems. When I use `check-jsonschema`, the script hangs and never exits. I've tried running it with `-v` and nothing is printed to the console.

The problem I have is that I have no clue of what can be hanging the script and I can't share the whole schema and json input I'm using because they belong to my company.

If somebody could help me give me a hint of where the problem can be, I can try to build a reproducible example. I'm using version 0.23.2.

Thank you!

**Comment by sirosen** [comment] 2023-08-30 21:35
I'm not sure what to do with this because I don't have enough information here to help even try to break down the problem.

I think you'll need to pull out part of the schema to find where the problem is and then share that as a MRE.
I can't really help you build a MRE with so little context though.

You'll need to find some part of the schema which, when removed, makes the problem go away.

**Comment by sirosen** [comment] 2023-08-31 14:47
@nicotrozzo reached out over email and we discussed his problem. Although it's not yet resolved, I think the issue is due to some regex syntax with quantifiers.
Since we're now discussing off-github, I'm going to close this.

Some items are quantified in patterns with `{1,}` and `{0,}`. I did a quick test and these mean `+` and `*` respectively. Although less obvious than nested `+` and `*` usage, it leads to the same catastrophic backtracking behaviors that nested `+` and `*` can cause.

**Closed by sirosen** 2023-08-31 14:47 UTC
Labels: question, needs-investigation
