### ISSUE TITLE
Empty (null) yaml files are passing schema validation even if schema does not allow null

### ISSUE THREAD

**Issue by ssbarnea** [python-jsonschema/check-jsonschema#153] opened 2022-09-14 09:07 UTC
I observed that passing an empty yaml file for validation reports success even if the schema itself does not allow it:

```
$ check-jsonschema -v -o json --schemafile f/ansible-meta.json negative_test/roles/empty_meta/meta/main.yml
{
  "status": "ok",
  "errors": []
}
```

I checked against the ajv validator and that one seems to be able to correctly report the file as invalid:

```
$ ajv validate -s f/ansible-meta.json -d negative_test/roles/empty_meta/meta/main.yml 
strict mode: missing type "object" for keyword "properties" at "https://raw.githubusercontent.com/ansible/schemas/main/f/ansible-meta.json#" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "https://raw.githubusercontent.com/ansible/schemas/main/f/ansible-meta.json#/if" (strictTypes)
strict mode: missing type "object" for keyword "required" at "https://raw.githubusercontent.com/ansible/schemas/main/f/ansible-meta.json#" (strictTypes)
strict mode: missing type "object" for keyword "additionalProperties" at "https://raw.githubusercontent.com/ansible/schemas/main/f/ansible-meta.json#" (strictTypes)
strict mode: missing type "object" for keyword "properties" at "https://raw.githubusercontent.com/ansible/schemas/main/f/ansible-meta.json#" (strictTypes)
schema f/ansible-meta.json is invalid
error: strict mode: unknown keyword: "markdownDescription"
```

**Comment by sirosen** [comment] 2022-09-14 16:58
I did a quick double-check on the YAML spec and I see that this should be `null`, and I also noticed the "(null)" in the issue title. So there's no ambiguity; I was wrong about that. I'll assume that all loaders therefore handle it correctly, as `ruamel.yaml` does.

When I'm able to spend more time on this, I'll try to reproduce, but a MWE would still be helpful. It may turn out to be a `jsonschema` issue, if a schema accepts `None` incorrectly.

**Comment by sirosen** [comment] 2022-09-14 23:59
I'm not able to reproduce this when I try.

The value of an empty file is correctly loaded as `null` (`None`), but I'm finding that schema validation correctly rejects this value for simple schemas.

My example:

schema.json:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object"
}
```
empty.yml:
```
```
CLI output:
```
$ check-jsonschema --schemafile schema.json empty.yml
Schema validation errors were encountered.
  empty.yml::$: None is not of type 'object'
```

**Comment by sirosen** [comment] 2022-10-04 19:00
I'm closing this as a CNR. If you can provide an example which demonstrates the issue, I'm happy to revisit.

**Closed by sirosen** 2022-10-04 19:00 UTC
Labels: bug
